import os
import re
from typing import Optional
from github import Github
from github.GithubException import GithubException
from models import PRInfo, CoverageSummary


class PRCreator:
    """Service for creating GitHub pull requests"""
    
    def __init__(self):
        self.github_token = os.getenv("GITHUB_TOKEN")
        self.github = Github(self.github_token) if self.github_token else None
    
    def _parse_repo_url(self, repo_url: str) -> tuple[str, str]:
        """Parse GitHub repo URL to extract owner and repo name"""
        # Handle formats:
        # https://github.com/owner/repo
        # https://github.com/owner/repo.git
        # git@github.com:owner/repo.git
        # owner/repo
        
        if not repo_url:
            raise ValueError("Repository URL is required")
        
        # Remove .git suffix
        repo_url = repo_url.rstrip('.git')
        
        # Extract owner/repo from URL
        patterns = [
            r'github\.com[:/]([^/]+)/([^/]+)',
            r'^([^/]+)/([^/]+)$',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, repo_url)
            if match:
                owner = match.group(1)
                repo = match.group(2)
                return owner, repo
        
        raise ValueError(f"Invalid repository URL format: {repo_url}")
    
    async def create_pr(
        self,
        repo_url: Optional[str],
        branch: str,
        function_name: str,
        coverage: CoverageSummary,
        run_id: str,
        patch_diff: str,
        test_content: str,
    ) -> PRInfo:
        """Create a GitHub pull request"""
        
        if not repo_url:
            return PRInfo(
                title=f"Add tests for {function_name}",
                body=f"""This PR adds comprehensive test coverage for `{function_name}`.

- Coverage: {coverage.lines}% lines, {coverage.branches}% branches
- Generated test suite
- Output location: `experiments/{run_id}/`

Generated by veritas-pytest.
""",
                url=None,
                changed_files=[f"experiments/{run_id}/test_{function_name}.py"],
            )
        
        if not self.github_token or not self.github:
            return PRInfo(
                title=f"Add tests for {function_name}",
                body=f"""This PR adds comprehensive test coverage for `{function_name}`.

- Coverage: {coverage.lines}% lines, {coverage.branches}% branches
- Generated test suite
- Output location: `experiments/{run_id}/`

Generated by veritas-pytest.

Note: GITHUB_TOKEN not configured. PR was not actually created.
""",
                url=None,
                changed_files=[f"experiments/{run_id}/test_{function_name}.py"],
            )
        
        try:
            # Parse repository URL
            owner, repo_name = self._parse_repo_url(repo_url)
            repo = self.github.get_repo(f"{owner}/{repo_name}")
            
            # Create a new branch for the PR
            pr_branch = f"veritas-pytest-{run_id}"
            base_branch = branch or "main"
            
            # Get the base branch reference
            base_ref = repo.get_git_ref(f"heads/{base_branch}")
            base_sha = base_ref.object.sha
            
            # Create new branch
            repo.create_git_ref(ref=f"refs/heads/{pr_branch}", sha=base_sha)
            
            # Use the test content passed in
            if not test_content:
                # Fallback: try to read from temp directory
                import os
                test_path = os.path.join("temp_runs", run_id, f"test_{function_name}.py")
                if os.path.exists(test_path):
                    with open(test_path, "r") as f:
                        test_content = f.read()
            
            if not test_content:
                raise ValueError("Test content is required to create PR")
            
            # Create file in the new branch
            file_path = f"experiments/{run_id}/test_{function_name}.py"
            repo.create_file(
                path=file_path,
                message=f"Add tests for {function_name} (veritas-pytest)",
                content=test_content,
                branch=pr_branch,
            )
            
            # Create pull request
            pr = repo.create_pull(
                title=f"Add tests for {function_name}",
                body=f"""This PR adds comprehensive test coverage for `{function_name}`.

- Coverage: {coverage.lines}% lines, {coverage.branches}% branches
- Generated test suite with veritas-pytest
- Output location: `experiments/{run_id}/`

Generated by veritas-pytest.
""",
                head=pr_branch,
                base=base_branch,
            )
            
            return PRInfo(
                title=pr.title,
                body=pr.body,
                url=pr.html_url,
                changed_files=[file_path],
            )
            
        except GithubException as e:
            error_msg = str(e)
            print(f"GitHub API error: {error_msg}")
            return PRInfo(
                title=f"Add tests for {function_name}",
                body=f"""This PR adds comprehensive test coverage for `{function_name}`.

- Coverage: {coverage.lines}% lines, {coverage.branches}% branches
- Generated test suite
- Output location: `experiments/{run_id}/`

Generated by veritas-pytest.

Error creating PR: {error_msg}
""",
                url=None,
                changed_files=[f"experiments/{run_id}/test_{function_name}.py"],
            )
        except Exception as e:
            error_msg = str(e)
            print(f"Error creating PR: {error_msg}")
            return PRInfo(
                title=f"Add tests for {function_name}",
                body=f"""This PR adds comprehensive test coverage for `{function_name}`.

- Coverage: {coverage.lines}% lines, {coverage.branches}% branches
- Generated test suite
- Output location: `experiments/{run_id}/`

Generated by veritas-pytest.

Error creating PR: {error_msg}
""",
                url=None,
                changed_files=[f"experiments/{run_id}/test_{function_name}.py"],
            )
